import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const jsContext = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    // Node.js built-in modules (available in Electron)
    "path",
    "url",
    "fs",
    "fs/promises",
    "child_process",
    "readline",
    "crypto",
    "os",
    "stream",
    "events",
    "util",
    "buffer",
    "net",
    "tls",
    "http",
    "https",
    "zlib",
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  define: {
    global: "window",
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
  },
  minify: false,
});

const cssContext = await esbuild.context({
  entryPoints: ["src/styles/index.css"],
  bundle: true,
  outfile: "styles.css",
  logLevel: "info",
  minify: false,
});

if (prod) {
  await Promise.all([jsContext.rebuild(), cssContext.rebuild()]);
  process.exit(0);
} else {
  await Promise.all([jsContext.watch(), cssContext.watch()]);
}
